apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backstage
resources:
  - namespace.yaml
  - cert-issuer.yaml
  - cf-cluster-issuer.yaml
  - postgres.yaml
  - backstage.yaml
  - ingress.yaml

